[tools]
editorconfig-checker = "3"
"pipx:pre-commit" = { version = "4", uvx = "true", uvx_args = "--with pre-commit-uv" }
"pipx:taplo" = { version = "0.9.3", uvx = "true" }
shellcheck = "0.11"
shfmt = "3"
uv = "0.9"
